Fix various actors

diff --git a/plan/actors/CHECKCONVERT b/plan/actors/CHECKCONVERT
--- a/plan/actors/CHECKCONVERT
+++ b/plan/actors/CHECKCONVERT
@@ -1,6 +1,6 @@
 #!/bin/sh
 if [ $(which convert 2>&1|grep ^/|wc -l) -lt 1 ]; then 
-   echo "failed:convert" 1>&2
+   echo "${SPECIALPREFIX}failed:convert" 1>&2
    echo "maybe install imagemagick" 1>&2
    rm -f .tmp/proof-convert
    exit 1
diff --git a/plan/actors/CHECKFONTFORGE b/plan/actors/CHECKFONTFORGE
--- a/plan/actors/CHECKFONTFORGE
+++ b/plan/actors/CHECKFONTFORGE
@@ -1,6 +1,6 @@
 #!/bin/sh
 if [ $(which fontforge 2>&1|grep ^/|wc -l) -lt 1 ]; then 
-   echo "failed:fontforge" 1>&2
+   echo "${SPECIALPREFIX}failed:fontforge" 1>&2
    rm -f .tmp/proof-fontforge
    exit 1
 fi
diff --git a/plan/actors/CHECKPDFTOPPM b/plan/actors/CHECKPDFTOPPM
--- a/plan/actors/CHECKPDFTOPPM
+++ b/plan/actors/CHECKPDFTOPPM
@@ -1,6 +1,6 @@
 #!/bin/sh
 if [ $(which pdftoppm 2>&1|grep ^/|wc -l) -lt 1 ]; then 
-   echo "failed:pdftoppm" 1>&2
+   echo "${SPECIALPREFIX}failed:pdftoppm" 1>&2
    echo "maybe install poppler-utils" 1>&2
    rm -f .tmp/proof-pdftoppm
    exit 1
diff --git a/plan/actors/CHECKPNGCRUSH b/plan/actors/CHECKPNGCRUSH
--- a/plan/actors/CHECKPNGCRUSH
+++ b/plan/actors/CHECKPNGCRUSH
@@ -1,6 +1,6 @@
 #!/bin/sh
 if [ $(which pngcrush 2>&1|grep ^/|wc -l) -lt 1 ]; then 
-   echo "failed:pngcrush" 1>&2
+   echo "${SPECIALPREFIX}failed:pngcrush" 1>&2
    rm -f .tmp/proof-pngcrush
    exit 1
 fi
diff --git a/plan/actors/CHECKTEX b/plan/actors/CHECKTEX
--- a/plan/actors/CHECKTEX
+++ b/plan/actors/CHECKTEX
@@ -1,6 +1,6 @@
 #!/bin/sh
 if [ $(which pdflatex 2>&1|grep ^/|wc -l) -lt 1 ]; then 
-   echo "failed:pdflatex" 1>&2
+   echo "${SPECIALPREFIX}failed:pdflatex" 1>&2
    rm -f .tmp/proof-tex
    exit 1
 fi
