Fix PIONS

diff --git a/plan/actors/PIONS b/plan/actors/PIONS
--- a/plan/actors/PIONS
+++ b/plan/actors/PIONS
@@ -1,3 +1,14 @@
 #!/bin/sh
 set -e
-cp pions/pions-ops.counters.txt pions/counters.txt
+fail() {
+    echo "${SPECIALPREFIX}failed:$1" 1>&2
+    exit 1
+}
+for i in "$@"; do
+    mkdir -p pions/targets
+    rm -f pions/${i}.depends.txt
+    gs -dEPSCrop -r20x20 -sDEVICE=ppm -SOutputFile=/dev/null -DBATCH -DNOPAUSE -q -SPREFIX="${SPECIALPREFIX}" -SHOMEDIR=. -SCURRENTDIR=./pions -SBOOTFILE=./library/bootstrap.ps  -SDEPENDS=pions/${i}.depends.txt -SLISTS=pions/${i}.counters.txt -sOutput=pions/${i}.pdf -DPDFOUTPUT pions/${i}.eps || fail "${i}"
+    echo "${SPECIALPREFIX}done:${i}" 1>&2
+    rm -rf pions/targets
+    grep ^[+*] pions/${i}.depends.txt |cut -c4-|grep -v ^pions/targets| LC_ALL=
+done
