Mechanics of build seems ok

diff --git a/plan/bin/AXIOM b/plan/bin/AXIOM
--- a/plan/bin/AXIOM
+++ b/plan/bin/AXIOM
@@ -1,7 +1,7 @@
 #!/bin/sh
 while [ "$1" ]; do
     if [ ! -f "$1" ]; then
-        echo "failed:$1" 1>&2
+        echo "${SPECIALPREFIX}failed:$1" 1>&2
         exit 1
     else
         echo "${SPECIALPREFIX}${1}" 1>&2
diff --git a/plan/bin/CHECKGIMP b/plan/bin/CHECKGIMP
--- a/plan/bin/CHECKGIMP
+++ b/plan/bin/CHECKGIMP
@@ -1,6 +1,6 @@
 #!/bin/sh
 if [ $(which gimp 2>&1|grep ^/|wc -l) -lt 1 ]; then 
-   echo "failed:gimp"e
+   echo "failed:gimp" 1>&2
    exit 1
    rm -f .tmp/proof-gimp
 fi
